# Generated by Django 4.2.5 on 2023-10-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moms', '0002_alter_foodsmodel_raw_material_alter_foodsmodel_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodsmodel',
            options={'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
        migrations.AlterModelOptions(
            name='momsmodel',
            options={'verbose_name': 'Mom', 'verbose_name_plural': 'Moms'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'verbose_name': 'RawMaterial', 'verbose_name_plural': 'RawMaterials'},
        ),
        migrations.AlterModelOptions(
            name='unitrawmaterials',
            options={'verbose_name': 'UnitRawMaterial', 'verbose_name_plural': 'UnitRawMaterials'},
        ),
        migrations.AlterModelTable(
            name='rawmaterial',
            table='RawMaterial',
        ),
        migrations.AlterModelTable(
            name='unitrawmaterials',
            table='UnitRawMaterials',
        ),
    ]
