# Generated by Django 4.2.5 on 2023-10-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moms', '0003_alter_foodsmodel_options_alter_momsmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsmodel',
            name='food_order',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
