# Generated by Django 4.2.5 on 2023-10-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
