# Generated by Django 4.2.5 on 2023-10-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_remove_foodsmodel_raw_material'),
        ('Company', '0002_companymodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.companymodel')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.foodsmodel')),
            ],
            options={
                'db_table': 'CompanySchedule',
            },
        ),
    ]
