# Generated by Django 4.2.5 on 2023-10-14 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='UserExperience')),
                ('text', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'UX',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('UX', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comment.userexperience')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.foodsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
    ]
