# Generated by Django 4.2.5 on 2023-10-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsmodel',
            name='raw_material',
            field=models.ManyToManyField(blank=True, null=True, to='Food.rawmaterial'),
        ),
    ]
