# Generated by Django 4.2.5 on 2023-10-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_alter_foodsmodel_raw_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsmodel',
            name='raw_material',
        ),
    ]
