# Generated by Django 4.2.5 on 2023-10-07 15:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Moms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(4)])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('products', models.ManyToManyField(to='Moms.foodsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Moms.momsmodel')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
