# Generated by Django 4.2.5 on 2023-10-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_rename_product_orderdetail_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
